=== aron123/SoftwareTesting/dao/resources/libraryDatabase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="database">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="users">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="user" type="userType" ></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="books">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="book" type="bookType"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="bookInstances">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="bookInstance" type="bookInstanceType"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="borrowings">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="borrowing" type="borrowingType"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="userKey">
            <xs:selector xpath="UserType/username"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:key>
        <xs:key name="bookKey">
            <xs:selector xpath="bookType/ISBN"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:key>
        <xs:key name="bookInstanceKey">
            <xs:selector xpath="bookInstanceType/inventoryNumber"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:key>
        <xs:key name="borrowingKey">
            <xs:selector xpath="borrowingType/borrowID"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:key>
        <xs:keyref refer="bookKey" name="instanceToBookRef">
            <xs:selector xpath="bookInstanceType/bookISBN"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:keyref>
        <xs:keyref refer="bookInstanceKey" name="borrowingToInstanceRef">
            <xs:selector xpath="borrowingType/bookInstanceInventoryNumber"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:keyref>
    </xs:element>
    
    
    <xs:complexType name="passwordType">
        <xs:sequence>
            <xs:element name="hashedPassword" type="xs:string"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="userRole">
        <xs:restriction base="xs:string">
            <xs:enumeration value="READER"></xs:enumeration>
            <xs:enumeration value="LIBRARIAN"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="userType" id="username">
        <xs:sequence>
            <xs:element name="username" type="xs:string"></xs:element>
            <xs:element name="password" type="passwordType"></xs:element>
            <xs:element name="firstname"></xs:element>
            <xs:element name="lastname"></xs:element>
            <xs:element name="email" type="xs:string"></xs:element>
            <xs:element name="mobileNumber" type="xs:string"></xs:element>
            <xs:element name="role" type="userRole"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="genreType" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Scifi"></xs:enumeration>
            <xs:enumeration value="Crimi"></xs:enumeration>
            <xs:enumeration value="Natural"></xs:enumeration>
            <xs:enumeration value="Fiction"></xs:enumeration>
            <xs:enumeration value="Horror"></xs:enumeration>
            <xs:enumeration value="Mystery"></xs:enumeration>
            <xs:enumeration value="Romance"></xs:enumeration>
            <xs:enumeration value="Science"></xs:enumeration>
            <xs:enumeration value="History"></xs:enumeration>
            <xs:enumeration value="Comics"></xs:enumeration>
            <xs:enumeration value="Guide"></xs:enumeration>
            <xs:enumeration value="Travel"></xs:enumeration>
            <xs:enumeration value="Other"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="bookType">
        <xs:sequence>
            <xs:element name="ISBN" type="xs:long"></xs:element>
            <xs:element name="author" type="xs:string"></xs:element>
            <xs:element name="title" type="xs:string"></xs:element>
            <xs:element name="publishDate" type="xs:int"></xs:element>
            <xs:element name="genre" type="genreType"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="bookInstanceType">
        <xs:sequence>
            <xs:element name="inventoryNumber" type="xs:long"></xs:element>
            <xs:element name="bookISBN" type="xs:long"></xs:element>
            <xs:element name="isLoaned" type="xs:boolean"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="borrowStatusType" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REQUESTED"></xs:enumeration>
            <xs:enumeration value="BORROWED"></xs:enumeration>
            <xs:enumeration value="RETURNED"></xs:enumeration>
            <xs:enumeration value="EXPIRED"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="borrowingType">
        <xs:sequence>
            <xs:element name="borrowID" type="xs:long"></xs:element>
            <xs:element name="readerUsername" type="xs:string"></xs:element>
            <xs:element name="creationDate" type="xs:date"></xs:element>
            <xs:element name="expirationDate" type="xs:date"></xs:element>
            <xs:element name="status" type="borrowStatusType"></xs:element>
            <xs:element name="bookInstanceInventoryNumber" type="xs:long"></xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== aron123/SoftwareTesting/dao/resources/database.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="libraryDatabase.xsd">
    <users>
        <user>
            <username>bela</username>
            <password>
                <hashedPassword>$2a$04$uXb8rTLKZFpEB4NIgb7pa.EcfYMDrF/srpoKzmKofDCNJsTIi5/ri</hashedPassword>
            </password>
            <name>
                <firstname>Bela</firstname>
                <lastname>Toth</lastname>
            </name>
            <email>bela.toth@example.com</email>
            <mobileNumber>06201234567</mobileNumber>
            <role>LIBRARIAN</role>
        </user>
        <user>
            <username>feri</username>
            <password>
                <hashedPassword>$2a$04$uXb8rTLKZFpEB4NIgb7pa.EcfYMDrF/srpoKzmKofDCNJsTIi5/ri</hashedPassword>
            </password>
            <name>
                <firstname>Ferenc</firstname>
                <lastname>Kovacs</lastname>
            </name>
            <email>kovfer@example.com</email>
            <mobileNumber>0680123456</mobileNumber>
            <role>READER</role>
        </user>
    </users>
    
    <books>
        <book>
            <ISBN>123456</ISBN>
            <author>Pasztor Lajos</author>
            <title>Utazas a Fold korul</title>
            <publishDate>2010</publishDate>
            <genre>Travel</genre>
        </book>
        <book>
            <ISBN>1234567</ISBN>
            <author>Nagy Kalman</author>
            <title>Analizis III.</title>
            <publishDate>2013</publishDate>
            <genre>Scifi</genre>
        </book>
    </books>
    
    <bookInstances>
        <bookInstance>
            <inventoryNumber>123456789</inventoryNumber>
            <bookISBN>123456</bookISBN>
            <isLoaned>false</isLoaned>
        </bookInstance>
        <bookInstance>
            <inventoryNumber>123456790</inventoryNumber>
            <bookISBN>123456</bookISBN>
            <isLoaned>true</isLoaned>
        </bookInstance>
        <bookInstance>
            <inventoryNumber>123456791</inventoryNumber>
            <bookISBN>1234567</bookISBN>
            <isLoaned>false</isLoaned>
        </bookInstance>
    </bookInstances>
    
    <borrowings>
        <borrowing>
            <borrowID>1234567</borrowID>
            <readerUsername>feri</readerUsername>
            <creationDate>2017-01-10</creationDate>
            <expirationDate>2017-02-26</expirationDate>
            <status>EXPIRED</status>
            <bookInstanceInventoryNumber>123456790</bookInstanceInventoryNumber>
        </borrowing>
        <borrowing>
            <borrowID>12345678</borrowID>
            <readerUsername>feri</readerUsername>
            <creationDate>2018-11-06</creationDate>
            <expirationDate>2019-01-01</expirationDate>
            <status>BORROWED</status>
            <bookInstanceInventoryNumber>123456790</bookInstanceInventoryNumber>
        </borrowing>
        <borrowing>
            <borrowID>2222345678</borrowID>
            <readerUsername>feri</readerUsername>
            <creationDate>2018-11-06</creationDate>
            <expirationDate>2019-01-01</expirationDate>
            <status>REQUESTED</status>
            <bookInstanceInventoryNumber>123456791</bookInstanceInventoryNumber>
        </borrowing>
    </borrowings>


</database>
